name = "blog-api"
main = "src/index.js"
compatibility_date = "2024-09-23"

[vars]
NOTION_DATABASE_ID = "750b48cd8a794e80955f3d0f2fa0b2b6"
ALLOWED_ORIGIN = "https://aleksanderone.website"
CACHE_TTL = "300"

# Secret (dodaj przez: wrangler secret put NOTION_API_TOKEN)
# NOTION_API_TOKEN = "secret_..."
